### PR TITLE
swig-wx formula rename and build system change

### PR DESCRIPTION
**Pull request by hawesie**
Homebrew doesn't like the hyphen in swig-wx so I've changed this to swigwx. It also appears that swig-wx uses autoconf not cmake, so I changed the formula to reflect this. These fixes may just hide underlying problems, so this is more of a cry for help rather than a super-serious pull request.

### CODE REVIEW

**Comment by wjwwood** [comment]
What does Homebrew not like about the hyphen?  In my experience that is ok, can you post the error it gives you.

The reason that the swig-wx formula is setup to use cmake is because most of the formula in this repository are auto-generated, I need to make an exception for the swig-wx formula so it will use autoconf instead of cmake.

I am working on the Fuerte on OS X as I get time, but it is currently sort of broken.

I'll keep you posted.

I am not going to merge this pull request because the swig-wx will be auto generated, but I will take the changes in to the auto generation of it in the future.

**Comment by hawesie** [comment]
The error I get is here

https://gist.github.com/2686896

I'm happy to help you out with Fuerte, but I'm still trying to get my head around where bits come from and why. Is there an issue list for the install at the moment?

**Comment by wjwwood** [comment]
This is again a problem with the auto generation I need to deal with.  You can have the formula name swig-wx but the class name needs to be Swig_Wx.

I would like to have some help with it, currently what I am trying to do is make it so Homebrew formula and pip requirement files are generated via the ros release file:

https://github.com/ros/rosdistro/blob/master/releases/fuerte.yaml

The reasons for this are: making it easy to keep the Homebrew formula up-to-date, making so that Homebrew can eventually be integrated into the release system along with Ubuntu, and to it easier for third parties to add Homebrew ROS packages.

Currently I am just working on the generation step and I haven't started putting it into the release system, and at some point it will also build the formula and bottle them for binary distribution.  You can see my generation script here:

https://github.com/ros/homebrew-fuerte/tree/master/distribution

Let me know if you have specific questions, I know from experience that this system is somewhat complex.

**Comment by hawesie** [comment]
Thanks, I'm starting to get a feel for it. I have a few other questions and issues that I've noticed as I've been trying to install today. Should we carry on discussing here or move to a different board. It would be good if there was an issues board for "ros/homebrew-fuerte" as that seems like the natural place to deal with the general things.

**Comment by wjwwood** [comment]
We can create issues on Github, or we can just have them out on the mailing
list.  Either way.

## 

```
William Woodall
Graduate Software Engineering
Auburn University
w@auburn.edu
wjwwood@gmail.com
williamjwoodall.com
```

On Sun, May 13, 2012 at 1:36 PM, Nick Hawes <
reply@reply.github.com

**Comment by hawesie** [comment]
I'd prefer GitHub as I suspect it will be better due to ability to discuss code diffs etc. directly. However, there isn't an issue board for ros or ros/homebrew-fuerte. Can you add one?

**Comment by wjwwood** [comment]
Issues are enabled now.

**Pull request closed without merging**
